/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MockRebasingRWAInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowance"
      | "approve"
      | "assetType"
      | "balanceOf"
      | "burn"
      | "decimals"
      | "mint"
      | "name"
      | "rebase"
      | "rebaseByUI"
      | "setDecimals"
      | "sharesOf"
      | "symbol"
      | "totalPooledAssets"
      | "totalShares"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Approval" | "Rebased" | "Transfer"): EventFragment;

  encodeFunctionData(functionFragment: "allowance", values: [AddressLike, AddressLike]): string;
  encodeFunctionData(functionFragment: "approve", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "assetType", values?: undefined): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "burn", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(functionFragment: "mint", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "rebase", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "rebaseByUI", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "setDecimals", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "sharesOf", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "totalPooledAssets", values?: undefined): string;
  encodeFunctionData(functionFragment: "totalShares", values?: undefined): string;
  encodeFunctionData(functionFragment: "totalSupply", values?: undefined): string;
  encodeFunctionData(functionFragment: "transfer", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "transferFrom", values: [AddressLike, AddressLike, BigNumberish]): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assetType", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rebase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rebaseByUI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setDecimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sharesOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalPooledAssets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalSupply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transferFrom", data: BytesLike): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebasedEvent {
  export type InputTuple = [yieldAdded: BigNumberish, newTotalPooledAssets: BigNumberish];
  export type OutputTuple = [yieldAdded: bigint, newTotalPooledAssets: bigint];
  export interface OutputObject {
    yieldAdded: bigint;
    newTotalPooledAssets: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockRebasingRWA extends BaseContract {
  connect(runner?: ContractRunner | null): MockRebasingRWA;
  waitForDeployment(): Promise<this>;

  interface: MockRebasingRWAInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  allowance: TypedContractMethod<[owner: AddressLike, spender: AddressLike], [bigint], "view">;

  approve: TypedContractMethod<[spender: AddressLike, amount: BigNumberish], [boolean], "nonpayable">;

  assetType: TypedContractMethod<[], [bigint], "view">;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  burn: TypedContractMethod<[from: AddressLike, amount: BigNumberish], [void], "nonpayable">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  mint: TypedContractMethod<[to: AddressLike, amount: BigNumberish], [void], "nonpayable">;

  name: TypedContractMethod<[], [string], "view">;

  rebase: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  rebaseByUI: TypedContractMethod<[basisPoints: BigNumberish], [void], "nonpayable">;

  setDecimals: TypedContractMethod<[decimals_: BigNumberish], [void], "nonpayable">;

  sharesOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  symbol: TypedContractMethod<[], [string], "view">;

  totalPooledAssets: TypedContractMethod<[], [bigint], "view">;

  totalShares: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<[to: AddressLike, amount: BigNumberish], [boolean], "nonpayable">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<[owner: AddressLike, spender: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<[spender: AddressLike, amount: BigNumberish], [boolean], "nonpayable">;
  getFunction(nameOrSignature: "assetType"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "balanceOf"): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<[from: AddressLike, amount: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "decimals"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<[to: AddressLike, amount: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "name"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "rebase"): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "rebaseByUI"): TypedContractMethod<[basisPoints: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "setDecimals"): TypedContractMethod<[decimals_: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "sharesOf"): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(nameOrSignature: "symbol"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "totalPooledAssets"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "totalShares"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "totalSupply"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<[to: AddressLike, amount: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<[from: AddressLike, to: AddressLike, amount: BigNumberish], [boolean], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
  getEvent(
    key: "Rebased"
  ): TypedContractEvent<RebasedEvent.InputTuple, RebasedEvent.OutputTuple, RebasedEvent.OutputObject>;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;

    "Rebased(uint256,uint256)": TypedContractEvent<
      RebasedEvent.InputTuple,
      RebasedEvent.OutputTuple,
      RebasedEvent.OutputObject
    >;
    Rebased: TypedContractEvent<RebasedEvent.InputTuple, RebasedEvent.OutputTuple, RebasedEvent.OutputObject>;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
  };
}
