/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MockComplianceAdapterInterface extends Interface {
  getFunction(nameOrSignature: "adapterType" | "isCompliant" | "willPass"): FunctionFragment;

  encodeFunctionData(functionFragment: "adapterType", values?: undefined): string;
  encodeFunctionData(functionFragment: "isCompliant", values: [AddressLike, AddressLike]): string;
  encodeFunctionData(functionFragment: "willPass", values?: undefined): string;

  decodeFunctionResult(functionFragment: "adapterType", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isCompliant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "willPass", data: BytesLike): Result;
}

export interface MockComplianceAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): MockComplianceAdapter;
  waitForDeployment(): Promise<this>;

  interface: MockComplianceAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  adapterType: TypedContractMethod<[], [string], "view">;

  isCompliant: TypedContractMethod<[arg0: AddressLike, arg1: AddressLike], [boolean], "view">;

  willPass: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: "adapterType"): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isCompliant"
  ): TypedContractMethod<[arg0: AddressLike, arg1: AddressLike], [boolean], "view">;
  getFunction(nameOrSignature: "willPass"): TypedContractMethod<[], [boolean], "view">;

  filters: {};
}
