/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PendleYieldAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "getYieldBps"
      | "marketConfigs"
      | "owner"
      | "pendingOwner"
      | "pendleOracle"
      | "renounceOwnership"
      | "setMarketConfig"
      | "setPendleOracle"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MarketConfigSet" | "OwnershipTransferStarted" | "OwnershipTransferred" | "PendleOracleSet"
  ): EventFragment;

  encodeFunctionData(functionFragment: "acceptOwnership", values?: undefined): string;
  encodeFunctionData(functionFragment: "getYieldBps", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "marketConfigs", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pendingOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pendleOracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "renounceOwnership", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMarketConfig",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setPendleOracle", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "transferOwnership", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "acceptOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getYieldBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "marketConfigs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendleOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renounceOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMarketConfig", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPendleOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transferOwnership", data: BytesLike): Result;
}

export namespace MarketConfigSetEvent {
  export type InputTuple = [
    asset: AddressLike,
    pendleMarket: AddressLike,
    ptToken: AddressLike,
    twapWindow: BigNumberish,
    maxYieldBps: BigNumberish,
  ];
  export type OutputTuple = [
    asset: string,
    pendleMarket: string,
    ptToken: string,
    twapWindow: bigint,
    maxYieldBps: bigint,
  ];
  export interface OutputObject {
    asset: string;
    pendleMarket: string;
    ptToken: string;
    twapWindow: bigint;
    maxYieldBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendleOracleSetEvent {
  export type InputTuple = [pendleOracle: AddressLike];
  export type OutputTuple = [pendleOracle: string];
  export interface OutputObject {
    pendleOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PendleYieldAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): PendleYieldAdapter;
  waitForDeployment(): Promise<this>;

  interface: PendleYieldAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  getYieldBps: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  marketConfigs: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint] & {
        pendleMarket: string;
        ptToken: string;
        twapWindow: bigint;
        maxYieldBps: bigint;
      },
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  pendleOracle: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMarketConfig: TypedContractMethod<
    [
      asset: AddressLike,
      pendleMarket: AddressLike,
      ptToken: AddressLike,
      twapWindow: BigNumberish,
      maxYieldBps: BigNumberish,
    ],
    [void],
    "nonpayable"
  >;

  setPendleOracle: TypedContractMethod<[_pendleOracle: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: "acceptOwnership"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(nameOrSignature: "getYieldBps"): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(nameOrSignature: "marketConfigs"): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint] & {
        pendleMarket: string;
        ptToken: string;
        twapWindow: bigint;
        maxYieldBps: bigint;
      },
    ],
    "view"
  >;
  getFunction(nameOrSignature: "owner"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "pendingOwner"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "pendleOracle"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "renounceOwnership"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMarketConfig"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      pendleMarket: AddressLike,
      ptToken: AddressLike,
      twapWindow: BigNumberish,
      maxYieldBps: BigNumberish,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPendleOracle"
  ): TypedContractMethod<[_pendleOracle: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "transferOwnership"): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MarketConfigSet"
  ): TypedContractEvent<
    MarketConfigSetEvent.InputTuple,
    MarketConfigSetEvent.OutputTuple,
    MarketConfigSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PendleOracleSet"
  ): TypedContractEvent<
    PendleOracleSetEvent.InputTuple,
    PendleOracleSetEvent.OutputTuple,
    PendleOracleSetEvent.OutputObject
  >;

  filters: {
    "MarketConfigSet(address,address,address,uint32,uint256)": TypedContractEvent<
      MarketConfigSetEvent.InputTuple,
      MarketConfigSetEvent.OutputTuple,
      MarketConfigSetEvent.OutputObject
    >;
    MarketConfigSet: TypedContractEvent<
      MarketConfigSetEvent.InputTuple,
      MarketConfigSetEvent.OutputTuple,
      MarketConfigSetEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PendleOracleSet(address)": TypedContractEvent<
      PendleOracleSetEvent.InputTuple,
      PendleOracleSetEvent.OutputTuple,
      PendleOracleSetEvent.OutputObject
    >;
    PendleOracleSet: TypedContractEvent<
      PendleOracleSetEvent.InputTuple,
      PendleOracleSetEvent.OutputTuple,
      PendleOracleSetEvent.OutputObject
    >;
  };
}
