/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface Periphery_IVaultInterface extends Interface {
  getFunction(
    nameOrSignature: "decreasePosition" | "fromWadAmount" | "getMinPrice" | "getPositionKey" | "isSoftLockedPosition"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "decreasePosition",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish, boolean, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fromWadAmount", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "getMinPrice", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getPositionKey",
    values: [AddressLike, AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "isSoftLockedPosition", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "decreasePosition", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fromWadAmount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMinPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPositionKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isSoftLockedPosition", data: BytesLike): Result;
}

export interface Periphery_IVault extends BaseContract {
  connect(runner?: ContractRunner | null): Periphery_IVault;
  waitForDeployment(): Promise<this>;

  interface: Periphery_IVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  decreasePosition: TypedContractMethod<
    [
      _account: AddressLike,
      _collateralToken: AddressLike,
      _indexToken: AddressLike,
      _collateralDelta: BigNumberish,
      _sizeDelta: BigNumberish,
      _isLong: boolean,
      _receiver: AddressLike,
      _acceptablePrice: BigNumberish,
    ],
    [bigint],
    "nonpayable"
  >;

  fromWadAmount: TypedContractMethod<[token: AddressLike, wadAmount: BigNumberish], [bigint], "view">;

  getMinPrice: TypedContractMethod<[_token: AddressLike], [bigint], "view">;

  getPositionKey: TypedContractMethod<
    [_account: AddressLike, _collateralToken: AddressLike, _indexToken: AddressLike, _isLong: boolean],
    [string],
    "view"
  >;

  isSoftLockedPosition: TypedContractMethod<[key: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: "decreasePosition"
  ): TypedContractMethod<
    [
      _account: AddressLike,
      _collateralToken: AddressLike,
      _indexToken: AddressLike,
      _collateralDelta: BigNumberish,
      _sizeDelta: BigNumberish,
      _isLong: boolean,
      _receiver: AddressLike,
      _acceptablePrice: BigNumberish,
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fromWadAmount"
  ): TypedContractMethod<[token: AddressLike, wadAmount: BigNumberish], [bigint], "view">;
  getFunction(nameOrSignature: "getMinPrice"): TypedContractMethod<[_token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPositionKey"
  ): TypedContractMethod<
    [_account: AddressLike, _collateralToken: AddressLike, _indexToken: AddressLike, _isLong: boolean],
    [string],
    "view"
  >;
  getFunction(nameOrSignature: "isSoftLockedPosition"): TypedContractMethod<[key: BytesLike], [boolean], "view">;

  filters: {};
}
