/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RevenueStoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "HUB_TIMELOCK"
      | "acceptOwnership"
      | "acceptVault"
      | "acceptWithdrawal"
      | "authorizedCallers"
      | "checkpoint"
      | "claim"
      | "debtCeilings"
      | "distribute"
      | "getHubHealth"
      | "getPhase"
      | "getReserveRatio"
      | "getTotalRemainingCapacity"
      | "globalPaused"
      | "isVaultIsolated"
      | "lastClaimedPayoutIndex"
      | "lastClaimedYieldIndex"
      | "minimumUsdcFloor"
      | "owner"
      | "payoutLpToken"
      | "payoutPool"
      | "payoutRewardIndex"
      | "pendingClaim"
      | "pendingOwner"
      | "pendingPayoutRewards"
      | "pendingVaultRegistrations"
      | "pendingWithdrawal"
      | "pendingYieldRewards"
      | "proposeVault"
      | "recordLoss"
      | "recordRevenue"
      | "recruitingPayoutShareBps"
      | "registeredVaults"
      | "renounceOwnership"
      | "requestPayout"
      | "revenueBalance"
      | "riskFactorBps"
      | "setAuthorizedCaller"
      | "setDebtCeiling"
      | "setGlobalPaused"
      | "setHaircut"
      | "setMinimumUsdcFloor"
      | "setRecruitingPayoutShare"
      | "setRiskFactor"
      | "setVaultIsolation"
      | "setVaultPaused"
      | "settleProfit"
      | "totalOutstandingDebt"
      | "totalRegisteredCeilings"
      | "transferOwnership"
      | "usdc"
      | "vaultDebts"
      | "vaultPaused"
      | "withdrawLiquidity"
      | "yieldHaircutBps"
      | "yieldLpToken"
      | "yieldPool"
      | "yieldRewardIndex"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claimed"
      | "DebtCeilingUpdated"
      | "Distributed"
      | "GlobalPauseSet"
      | "HaircutSet"
      | "LiquidityWithdrawn"
      | "LossRecorded"
      | "MinimumUsdcFloorSet"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "PayoutRequested"
      | "PhaseChanged"
      | "ProfitSettled"
      | "RecruitingPayoutShareSet"
      | "RevenueRecorded"
      | "RiskFactorSet"
      | "VaultIsolationSet"
      | "VaultPauseSet"
      | "VaultRegistered"
      | "VaultRegistrationProposed"
      | "WithdrawalProposed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "HUB_TIMELOCK", values?: undefined): string;
  encodeFunctionData(functionFragment: "acceptOwnership", values?: undefined): string;
  encodeFunctionData(functionFragment: "acceptVault", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "acceptWithdrawal", values?: undefined): string;
  encodeFunctionData(functionFragment: "authorizedCallers", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "checkpoint", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "claim", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "debtCeilings", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "distribute", values?: undefined): string;
  encodeFunctionData(functionFragment: "getHubHealth", values: [AddressLike[]]): string;
  encodeFunctionData(functionFragment: "getPhase", values?: undefined): string;
  encodeFunctionData(functionFragment: "getReserveRatio", values?: undefined): string;
  encodeFunctionData(functionFragment: "getTotalRemainingCapacity", values?: undefined): string;
  encodeFunctionData(functionFragment: "globalPaused", values?: undefined): string;
  encodeFunctionData(functionFragment: "isVaultIsolated", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "lastClaimedPayoutIndex", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "lastClaimedYieldIndex", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "minimumUsdcFloor", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "payoutLpToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "payoutPool", values?: undefined): string;
  encodeFunctionData(functionFragment: "payoutRewardIndex", values?: undefined): string;
  encodeFunctionData(functionFragment: "pendingClaim", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "pendingOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pendingPayoutRewards", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "pendingVaultRegistrations", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "pendingWithdrawal", values?: undefined): string;
  encodeFunctionData(functionFragment: "pendingYieldRewards", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "proposeVault", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "recordLoss", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "recordRevenue", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "recruitingPayoutShareBps", values?: undefined): string;
  encodeFunctionData(functionFragment: "registeredVaults", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "renounceOwnership", values?: undefined): string;
  encodeFunctionData(functionFragment: "requestPayout", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "revenueBalance", values?: undefined): string;
  encodeFunctionData(functionFragment: "riskFactorBps", values?: undefined): string;
  encodeFunctionData(functionFragment: "setAuthorizedCaller", values: [AddressLike, boolean]): string;
  encodeFunctionData(functionFragment: "setDebtCeiling", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "setGlobalPaused", values: [boolean]): string;
  encodeFunctionData(functionFragment: "setHaircut", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "setMinimumUsdcFloor", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "setRecruitingPayoutShare", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "setRiskFactor", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "setVaultIsolation", values: [AddressLike, boolean]): string;
  encodeFunctionData(functionFragment: "setVaultPaused", values: [AddressLike, boolean]): string;
  encodeFunctionData(functionFragment: "settleProfit", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "totalOutstandingDebt", values?: undefined): string;
  encodeFunctionData(functionFragment: "totalRegisteredCeilings", values?: undefined): string;
  encodeFunctionData(functionFragment: "transferOwnership", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(functionFragment: "vaultDebts", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "vaultPaused", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "withdrawLiquidity", values: [BigNumberish, AddressLike]): string;
  encodeFunctionData(functionFragment: "yieldHaircutBps", values?: undefined): string;
  encodeFunctionData(functionFragment: "yieldLpToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "yieldPool", values?: undefined): string;
  encodeFunctionData(functionFragment: "yieldRewardIndex", values?: undefined): string;

  decodeFunctionResult(functionFragment: "HUB_TIMELOCK", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "acceptOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "acceptVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "acceptWithdrawal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "authorizedCallers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkpoint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "debtCeilings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distribute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getHubHealth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPhase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getReserveRatio", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTotalRemainingCapacity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "globalPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isVaultIsolated", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastClaimedPayoutIndex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastClaimedYieldIndex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minimumUsdcFloor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payoutLpToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payoutPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payoutRewardIndex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingPayoutRewards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingVaultRegistrations", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingWithdrawal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingYieldRewards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proposeVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordLoss", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordRevenue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recruitingPayoutShareBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registeredVaults", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renounceOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "requestPayout", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revenueBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "riskFactorBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAuthorizedCaller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setDebtCeiling", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setGlobalPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setHaircut", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMinimumUsdcFloor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRecruitingPayoutShare", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRiskFactor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setVaultIsolation", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setVaultPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settleProfit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalOutstandingDebt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalRegisteredCeilings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transferOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaultDebts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaultPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdrawLiquidity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yieldHaircutBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yieldLpToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yieldPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yieldRewardIndex", data: BytesLike): Result;
}

export namespace ClaimedEvent {
  export type InputTuple = [lp: AddressLike, amount: BigNumberish];
  export type OutputTuple = [lp: string, amount: bigint];
  export interface OutputObject {
    lp: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebtCeilingUpdatedEvent {
  export type InputTuple = [vault: AddressLike, oldCeiling: BigNumberish, newCeiling: BigNumberish];
  export type OutputTuple = [vault: string, oldCeiling: bigint, newCeiling: bigint];
  export interface OutputObject {
    vault: string;
    oldCeiling: bigint;
    newCeiling: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributedEvent {
  export type InputTuple = [payoutShare: BigNumberish, yieldShare: BigNumberish, phase: BigNumberish];
  export type OutputTuple = [payoutShare: bigint, yieldShare: bigint, phase: bigint];
  export interface OutputObject {
    payoutShare: bigint;
    yieldShare: bigint;
    phase: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalPauseSetEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HaircutSetEvent {
  export type InputTuple = [bps: BigNumberish];
  export type OutputTuple = [bps: bigint];
  export interface OutputObject {
    bps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LossRecordedEvent {
  export type InputTuple = [amount: BigNumberish, newBalance: BigNumberish];
  export type OutputTuple = [amount: bigint, newBalance: bigint];
  export interface OutputObject {
    amount: bigint;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinimumUsdcFloorSetEvent {
  export type InputTuple = [floor: BigNumberish];
  export type OutputTuple = [floor: bigint];
  export interface OutputObject {
    floor: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutRequestedEvent {
  export type InputTuple = [vault: AddressLike, receiver: AddressLike, amount: BigNumberish];
  export type OutputTuple = [vault: string, receiver: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    receiver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PhaseChangedEvent {
  export type InputTuple = [newPhase: BigNumberish, reserveRatioBps: BigNumberish];
  export type OutputTuple = [newPhase: bigint, reserveRatioBps: bigint];
  export interface OutputObject {
    newPhase: bigint;
    reserveRatioBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfitSettledEvent {
  export type InputTuple = [vault: AddressLike, payer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [vault: string, payer: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    payer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecruitingPayoutShareSetEvent {
  export type InputTuple = [bps: BigNumberish];
  export type OutputTuple = [bps: bigint];
  export interface OutputObject {
    bps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueRecordedEvent {
  export type InputTuple = [amount: BigNumberish, newBalance: BigNumberish];
  export type OutputTuple = [amount: bigint, newBalance: bigint];
  export interface OutputObject {
    amount: bigint;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskFactorSetEvent {
  export type InputTuple = [bps: BigNumberish];
  export type OutputTuple = [bps: bigint];
  export interface OutputObject {
    bps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultIsolationSetEvent {
  export type InputTuple = [vault: AddressLike, isolated: boolean];
  export type OutputTuple = [vault: string, isolated: boolean];
  export interface OutputObject {
    vault: string;
    isolated: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultPauseSetEvent {
  export type InputTuple = [vault: AddressLike, paused: boolean];
  export type OutputTuple = [vault: string, paused: boolean];
  export interface OutputObject {
    vault: string;
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultRegisteredEvent {
  export type InputTuple = [vault: AddressLike, debtCeiling: BigNumberish];
  export type OutputTuple = [vault: string, debtCeiling: bigint];
  export interface OutputObject {
    vault: string;
    debtCeiling: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultRegistrationProposedEvent {
  export type InputTuple = [vault: AddressLike, ceiling: BigNumberish, executableAt: BigNumberish];
  export type OutputTuple = [vault: string, ceiling: bigint, executableAt: bigint];
  export interface OutputObject {
    vault: string;
    ceiling: bigint;
    executableAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalProposedEvent {
  export type InputTuple = [amount: BigNumberish, to: AddressLike, executableAt: BigNumberish];
  export type OutputTuple = [amount: bigint, to: string, executableAt: bigint];
  export interface OutputObject {
    amount: bigint;
    to: string;
    executableAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RevenueStore extends BaseContract {
  connect(runner?: ContractRunner | null): RevenueStore;
  waitForDeployment(): Promise<this>;

  interface: RevenueStoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  HUB_TIMELOCK: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  acceptVault: TypedContractMethod<[vault: AddressLike], [void], "nonpayable">;

  acceptWithdrawal: TypedContractMethod<[], [void], "nonpayable">;

  authorizedCallers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  checkpoint: TypedContractMethod<[lp: AddressLike], [void], "nonpayable">;

  claim: TypedContractMethod<[lp: AddressLike], [bigint], "nonpayable">;

  debtCeilings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  distribute: TypedContractMethod<[], [void], "nonpayable">;

  getHubHealth: TypedContractMethod<
    [vaults: AddressLike[]],
    [[bigint, bigint] & { usdcBalance: bigint; totalDebt: bigint }],
    "view"
  >;

  getPhase: TypedContractMethod<[], [bigint], "view">;

  getReserveRatio: TypedContractMethod<[], [bigint], "view">;

  getTotalRemainingCapacity: TypedContractMethod<[], [bigint], "view">;

  globalPaused: TypedContractMethod<[], [boolean], "view">;

  isVaultIsolated: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lastClaimedPayoutIndex: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  lastClaimedYieldIndex: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  minimumUsdcFloor: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payoutLpToken: TypedContractMethod<[], [string], "view">;

  payoutPool: TypedContractMethod<[], [string], "view">;

  payoutRewardIndex: TypedContractMethod<[], [bigint], "view">;

  pendingClaim: TypedContractMethod<[lp: AddressLike], [bigint], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  pendingPayoutRewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  pendingVaultRegistrations: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { ceiling: bigint; executableAt: bigint }],
    "view"
  >;

  pendingWithdrawal: TypedContractMethod<
    [],
    [
      [bigint, string, bigint] & {
        amount: bigint;
        to: string;
        executableAt: bigint;
      },
    ],
    "view"
  >;

  pendingYieldRewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  proposeVault: TypedContractMethod<[vault: AddressLike, ceiling: BigNumberish], [void], "nonpayable">;

  recordLoss: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  recordRevenue: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  recruitingPayoutShareBps: TypedContractMethod<[], [bigint], "view">;

  registeredVaults: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestPayout: TypedContractMethod<[receiver: AddressLike, amount: BigNumberish], [void], "nonpayable">;

  revenueBalance: TypedContractMethod<[], [bigint], "view">;

  riskFactorBps: TypedContractMethod<[], [bigint], "view">;

  setAuthorizedCaller: TypedContractMethod<[caller: AddressLike, authorized: boolean], [void], "nonpayable">;

  setDebtCeiling: TypedContractMethod<[vault: AddressLike, newCeiling: BigNumberish], [void], "nonpayable">;

  setGlobalPaused: TypedContractMethod<[paused: boolean], [void], "nonpayable">;

  setHaircut: TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;

  setMinimumUsdcFloor: TypedContractMethod<[_floor: BigNumberish], [void], "nonpayable">;

  setRecruitingPayoutShare: TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;

  setRiskFactor: TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;

  setVaultIsolation: TypedContractMethod<[vault: AddressLike, isolated: boolean], [void], "nonpayable">;

  setVaultPaused: TypedContractMethod<[vault: AddressLike, paused: boolean], [void], "nonpayable">;

  settleProfit: TypedContractMethod<[_vault: AddressLike, amount: BigNumberish], [void], "nonpayable">;

  totalOutstandingDebt: TypedContractMethod<[], [bigint], "view">;

  totalRegisteredCeilings: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  usdc: TypedContractMethod<[], [string], "view">;

  vaultDebts: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  vaultPaused: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  withdrawLiquidity: TypedContractMethod<[amount: BigNumberish, to: AddressLike], [void], "nonpayable">;

  yieldHaircutBps: TypedContractMethod<[], [bigint], "view">;

  yieldLpToken: TypedContractMethod<[], [string], "view">;

  yieldPool: TypedContractMethod<[], [string], "view">;

  yieldRewardIndex: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: "HUB_TIMELOCK"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "acceptOwnership"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(nameOrSignature: "acceptVault"): TypedContractMethod<[vault: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "acceptWithdrawal"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(nameOrSignature: "authorizedCallers"): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(nameOrSignature: "checkpoint"): TypedContractMethod<[lp: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "claim"): TypedContractMethod<[lp: AddressLike], [bigint], "nonpayable">;
  getFunction(nameOrSignature: "debtCeilings"): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(nameOrSignature: "distribute"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getHubHealth"
  ): TypedContractMethod<
    [vaults: AddressLike[]],
    [[bigint, bigint] & { usdcBalance: bigint; totalDebt: bigint }],
    "view"
  >;
  getFunction(nameOrSignature: "getPhase"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "getReserveRatio"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "getTotalRemainingCapacity"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "globalPaused"): TypedContractMethod<[], [boolean], "view">;
  getFunction(nameOrSignature: "isVaultIsolated"): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(nameOrSignature: "lastClaimedPayoutIndex"): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(nameOrSignature: "lastClaimedYieldIndex"): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(nameOrSignature: "minimumUsdcFloor"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "owner"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "payoutLpToken"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "payoutPool"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "payoutRewardIndex"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "pendingClaim"): TypedContractMethod<[lp: AddressLike], [bigint], "view">;
  getFunction(nameOrSignature: "pendingOwner"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "pendingPayoutRewards"): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingVaultRegistrations"
  ): TypedContractMethod<[arg0: AddressLike], [[bigint, bigint] & { ceiling: bigint; executableAt: bigint }], "view">;
  getFunction(nameOrSignature: "pendingWithdrawal"): TypedContractMethod<
    [],
    [
      [bigint, string, bigint] & {
        amount: bigint;
        to: string;
        executableAt: bigint;
      },
    ],
    "view"
  >;
  getFunction(nameOrSignature: "pendingYieldRewards"): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposeVault"
  ): TypedContractMethod<[vault: AddressLike, ceiling: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "recordLoss"): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "recordRevenue"): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "recruitingPayoutShareBps"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "registeredVaults"): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(nameOrSignature: "renounceOwnership"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestPayout"
  ): TypedContractMethod<[receiver: AddressLike, amount: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "revenueBalance"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "riskFactorBps"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAuthorizedCaller"
  ): TypedContractMethod<[caller: AddressLike, authorized: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDebtCeiling"
  ): TypedContractMethod<[vault: AddressLike, newCeiling: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "setGlobalPaused"): TypedContractMethod<[paused: boolean], [void], "nonpayable">;
  getFunction(nameOrSignature: "setHaircut"): TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinimumUsdcFloor"
  ): TypedContractMethod<[_floor: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRecruitingPayoutShare"
  ): TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "setRiskFactor"): TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVaultIsolation"
  ): TypedContractMethod<[vault: AddressLike, isolated: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVaultPaused"
  ): TypedContractMethod<[vault: AddressLike, paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleProfit"
  ): TypedContractMethod<[_vault: AddressLike, amount: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "totalOutstandingDebt"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "totalRegisteredCeilings"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "transferOwnership"): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "usdc"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "vaultDebts"): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(nameOrSignature: "vaultPaused"): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawLiquidity"
  ): TypedContractMethod<[amount: BigNumberish, to: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "yieldHaircutBps"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "yieldLpToken"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "yieldPool"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "yieldRewardIndex"): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Claimed"
  ): TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
  getEvent(
    key: "DebtCeilingUpdated"
  ): TypedContractEvent<
    DebtCeilingUpdatedEvent.InputTuple,
    DebtCeilingUpdatedEvent.OutputTuple,
    DebtCeilingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Distributed"
  ): TypedContractEvent<DistributedEvent.InputTuple, DistributedEvent.OutputTuple, DistributedEvent.OutputObject>;
  getEvent(
    key: "GlobalPauseSet"
  ): TypedContractEvent<
    GlobalPauseSetEvent.InputTuple,
    GlobalPauseSetEvent.OutputTuple,
    GlobalPauseSetEvent.OutputObject
  >;
  getEvent(
    key: "HaircutSet"
  ): TypedContractEvent<HaircutSetEvent.InputTuple, HaircutSetEvent.OutputTuple, HaircutSetEvent.OutputObject>;
  getEvent(
    key: "LiquidityWithdrawn"
  ): TypedContractEvent<
    LiquidityWithdrawnEvent.InputTuple,
    LiquidityWithdrawnEvent.OutputTuple,
    LiquidityWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "LossRecorded"
  ): TypedContractEvent<LossRecordedEvent.InputTuple, LossRecordedEvent.OutputTuple, LossRecordedEvent.OutputObject>;
  getEvent(
    key: "MinimumUsdcFloorSet"
  ): TypedContractEvent<
    MinimumUsdcFloorSetEvent.InputTuple,
    MinimumUsdcFloorSetEvent.OutputTuple,
    MinimumUsdcFloorSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayoutRequested"
  ): TypedContractEvent<
    PayoutRequestedEvent.InputTuple,
    PayoutRequestedEvent.OutputTuple,
    PayoutRequestedEvent.OutputObject
  >;
  getEvent(
    key: "PhaseChanged"
  ): TypedContractEvent<PhaseChangedEvent.InputTuple, PhaseChangedEvent.OutputTuple, PhaseChangedEvent.OutputObject>;
  getEvent(
    key: "ProfitSettled"
  ): TypedContractEvent<ProfitSettledEvent.InputTuple, ProfitSettledEvent.OutputTuple, ProfitSettledEvent.OutputObject>;
  getEvent(
    key: "RecruitingPayoutShareSet"
  ): TypedContractEvent<
    RecruitingPayoutShareSetEvent.InputTuple,
    RecruitingPayoutShareSetEvent.OutputTuple,
    RecruitingPayoutShareSetEvent.OutputObject
  >;
  getEvent(
    key: "RevenueRecorded"
  ): TypedContractEvent<
    RevenueRecordedEvent.InputTuple,
    RevenueRecordedEvent.OutputTuple,
    RevenueRecordedEvent.OutputObject
  >;
  getEvent(
    key: "RiskFactorSet"
  ): TypedContractEvent<RiskFactorSetEvent.InputTuple, RiskFactorSetEvent.OutputTuple, RiskFactorSetEvent.OutputObject>;
  getEvent(
    key: "VaultIsolationSet"
  ): TypedContractEvent<
    VaultIsolationSetEvent.InputTuple,
    VaultIsolationSetEvent.OutputTuple,
    VaultIsolationSetEvent.OutputObject
  >;
  getEvent(
    key: "VaultPauseSet"
  ): TypedContractEvent<VaultPauseSetEvent.InputTuple, VaultPauseSetEvent.OutputTuple, VaultPauseSetEvent.OutputObject>;
  getEvent(
    key: "VaultRegistered"
  ): TypedContractEvent<
    VaultRegisteredEvent.InputTuple,
    VaultRegisteredEvent.OutputTuple,
    VaultRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VaultRegistrationProposed"
  ): TypedContractEvent<
    VaultRegistrationProposedEvent.InputTuple,
    VaultRegistrationProposedEvent.OutputTuple,
    VaultRegistrationProposedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalProposed"
  ): TypedContractEvent<
    WithdrawalProposedEvent.InputTuple,
    WithdrawalProposedEvent.OutputTuple,
    WithdrawalProposedEvent.OutputObject
  >;

  filters: {
    "Claimed(address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;

    "DebtCeilingUpdated(address,uint256,uint256)": TypedContractEvent<
      DebtCeilingUpdatedEvent.InputTuple,
      DebtCeilingUpdatedEvent.OutputTuple,
      DebtCeilingUpdatedEvent.OutputObject
    >;
    DebtCeilingUpdated: TypedContractEvent<
      DebtCeilingUpdatedEvent.InputTuple,
      DebtCeilingUpdatedEvent.OutputTuple,
      DebtCeilingUpdatedEvent.OutputObject
    >;

    "Distributed(uint256,uint256,uint8)": TypedContractEvent<
      DistributedEvent.InputTuple,
      DistributedEvent.OutputTuple,
      DistributedEvent.OutputObject
    >;
    Distributed: TypedContractEvent<
      DistributedEvent.InputTuple,
      DistributedEvent.OutputTuple,
      DistributedEvent.OutputObject
    >;

    "GlobalPauseSet(bool)": TypedContractEvent<
      GlobalPauseSetEvent.InputTuple,
      GlobalPauseSetEvent.OutputTuple,
      GlobalPauseSetEvent.OutputObject
    >;
    GlobalPauseSet: TypedContractEvent<
      GlobalPauseSetEvent.InputTuple,
      GlobalPauseSetEvent.OutputTuple,
      GlobalPauseSetEvent.OutputObject
    >;

    "HaircutSet(uint256)": TypedContractEvent<
      HaircutSetEvent.InputTuple,
      HaircutSetEvent.OutputTuple,
      HaircutSetEvent.OutputObject
    >;
    HaircutSet: TypedContractEvent<
      HaircutSetEvent.InputTuple,
      HaircutSetEvent.OutputTuple,
      HaircutSetEvent.OutputObject
    >;

    "LiquidityWithdrawn(address,uint256)": TypedContractEvent<
      LiquidityWithdrawnEvent.InputTuple,
      LiquidityWithdrawnEvent.OutputTuple,
      LiquidityWithdrawnEvent.OutputObject
    >;
    LiquidityWithdrawn: TypedContractEvent<
      LiquidityWithdrawnEvent.InputTuple,
      LiquidityWithdrawnEvent.OutputTuple,
      LiquidityWithdrawnEvent.OutputObject
    >;

    "LossRecorded(uint256,int256)": TypedContractEvent<
      LossRecordedEvent.InputTuple,
      LossRecordedEvent.OutputTuple,
      LossRecordedEvent.OutputObject
    >;
    LossRecorded: TypedContractEvent<
      LossRecordedEvent.InputTuple,
      LossRecordedEvent.OutputTuple,
      LossRecordedEvent.OutputObject
    >;

    "MinimumUsdcFloorSet(uint256)": TypedContractEvent<
      MinimumUsdcFloorSetEvent.InputTuple,
      MinimumUsdcFloorSetEvent.OutputTuple,
      MinimumUsdcFloorSetEvent.OutputObject
    >;
    MinimumUsdcFloorSet: TypedContractEvent<
      MinimumUsdcFloorSetEvent.InputTuple,
      MinimumUsdcFloorSetEvent.OutputTuple,
      MinimumUsdcFloorSetEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayoutRequested(address,address,uint256)": TypedContractEvent<
      PayoutRequestedEvent.InputTuple,
      PayoutRequestedEvent.OutputTuple,
      PayoutRequestedEvent.OutputObject
    >;
    PayoutRequested: TypedContractEvent<
      PayoutRequestedEvent.InputTuple,
      PayoutRequestedEvent.OutputTuple,
      PayoutRequestedEvent.OutputObject
    >;

    "PhaseChanged(uint8,uint256)": TypedContractEvent<
      PhaseChangedEvent.InputTuple,
      PhaseChangedEvent.OutputTuple,
      PhaseChangedEvent.OutputObject
    >;
    PhaseChanged: TypedContractEvent<
      PhaseChangedEvent.InputTuple,
      PhaseChangedEvent.OutputTuple,
      PhaseChangedEvent.OutputObject
    >;

    "ProfitSettled(address,address,uint256)": TypedContractEvent<
      ProfitSettledEvent.InputTuple,
      ProfitSettledEvent.OutputTuple,
      ProfitSettledEvent.OutputObject
    >;
    ProfitSettled: TypedContractEvent<
      ProfitSettledEvent.InputTuple,
      ProfitSettledEvent.OutputTuple,
      ProfitSettledEvent.OutputObject
    >;

    "RecruitingPayoutShareSet(uint256)": TypedContractEvent<
      RecruitingPayoutShareSetEvent.InputTuple,
      RecruitingPayoutShareSetEvent.OutputTuple,
      RecruitingPayoutShareSetEvent.OutputObject
    >;
    RecruitingPayoutShareSet: TypedContractEvent<
      RecruitingPayoutShareSetEvent.InputTuple,
      RecruitingPayoutShareSetEvent.OutputTuple,
      RecruitingPayoutShareSetEvent.OutputObject
    >;

    "RevenueRecorded(uint256,int256)": TypedContractEvent<
      RevenueRecordedEvent.InputTuple,
      RevenueRecordedEvent.OutputTuple,
      RevenueRecordedEvent.OutputObject
    >;
    RevenueRecorded: TypedContractEvent<
      RevenueRecordedEvent.InputTuple,
      RevenueRecordedEvent.OutputTuple,
      RevenueRecordedEvent.OutputObject
    >;

    "RiskFactorSet(uint256)": TypedContractEvent<
      RiskFactorSetEvent.InputTuple,
      RiskFactorSetEvent.OutputTuple,
      RiskFactorSetEvent.OutputObject
    >;
    RiskFactorSet: TypedContractEvent<
      RiskFactorSetEvent.InputTuple,
      RiskFactorSetEvent.OutputTuple,
      RiskFactorSetEvent.OutputObject
    >;

    "VaultIsolationSet(address,bool)": TypedContractEvent<
      VaultIsolationSetEvent.InputTuple,
      VaultIsolationSetEvent.OutputTuple,
      VaultIsolationSetEvent.OutputObject
    >;
    VaultIsolationSet: TypedContractEvent<
      VaultIsolationSetEvent.InputTuple,
      VaultIsolationSetEvent.OutputTuple,
      VaultIsolationSetEvent.OutputObject
    >;

    "VaultPauseSet(address,bool)": TypedContractEvent<
      VaultPauseSetEvent.InputTuple,
      VaultPauseSetEvent.OutputTuple,
      VaultPauseSetEvent.OutputObject
    >;
    VaultPauseSet: TypedContractEvent<
      VaultPauseSetEvent.InputTuple,
      VaultPauseSetEvent.OutputTuple,
      VaultPauseSetEvent.OutputObject
    >;

    "VaultRegistered(address,uint256)": TypedContractEvent<
      VaultRegisteredEvent.InputTuple,
      VaultRegisteredEvent.OutputTuple,
      VaultRegisteredEvent.OutputObject
    >;
    VaultRegistered: TypedContractEvent<
      VaultRegisteredEvent.InputTuple,
      VaultRegisteredEvent.OutputTuple,
      VaultRegisteredEvent.OutputObject
    >;

    "VaultRegistrationProposed(address,uint256,uint256)": TypedContractEvent<
      VaultRegistrationProposedEvent.InputTuple,
      VaultRegistrationProposedEvent.OutputTuple,
      VaultRegistrationProposedEvent.OutputObject
    >;
    VaultRegistrationProposed: TypedContractEvent<
      VaultRegistrationProposedEvent.InputTuple,
      VaultRegistrationProposedEvent.OutputTuple,
      VaultRegistrationProposedEvent.OutputObject
    >;

    "WithdrawalProposed(uint256,address,uint256)": TypedContractEvent<
      WithdrawalProposedEvent.InputTuple,
      WithdrawalProposedEvent.OutputTuple,
      WithdrawalProposedEvent.OutputObject
    >;
    WithdrawalProposed: TypedContractEvent<
      WithdrawalProposedEvent.InputTuple,
      WithdrawalProposedEvent.OutputTuple,
      WithdrawalProposedEvent.OutputObject
    >;
  };
}
