/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface YieldAccumulatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assetYields"
      | "getAccumulatedYield"
      | "owner"
      | "registerAsset"
      | "renounceOwnership"
      | "setAnnualYield"
      | "transferOwnership"
      | "updateYield"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AnnualYieldSet"
      | "OwnershipTransferred"
      | "YieldUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assetYields",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccumulatedYield",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAnnualYield",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateYield",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "assetYields",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccumulatedYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAnnualYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateYield",
    data: BytesLike
  ): Result;
}

export namespace AnnualYieldSetEvent {
  export type InputTuple = [
    asset: AddressLike,
    oldYieldBps: BigNumberish,
    newYieldBps: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    oldYieldBps: bigint,
    newYieldBps: bigint
  ];
  export interface OutputObject {
    asset: string;
    oldYieldBps: bigint;
    newYieldBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldUpdatedEvent {
  export type InputTuple = [
    asset: AddressLike,
    yieldDelta: BigNumberish,
    accumulatedYield: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    yieldDelta: bigint,
    accumulatedYield: bigint
  ];
  export interface OutputObject {
    asset: string;
    yieldDelta: bigint;
    accumulatedYield: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YieldAccumulator extends BaseContract {
  connect(runner?: ContractRunner | null): YieldAccumulator;
  waitForDeployment(): Promise<this>;

  interface: YieldAccumulatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assetYields: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        accumulatedYield: bigint;
        lastUpdated: bigint;
        annualYieldBps: bigint;
      }
    ],
    "view"
  >;

  getAccumulatedYield: TypedContractMethod<
    [asset: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerAsset: TypedContractMethod<
    [asset: AddressLike, yieldBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAnnualYield: TypedContractMethod<
    [asset: AddressLike, rawPrice: BigNumberish, yieldBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateYield: TypedContractMethod<
    [asset: AddressLike, rawPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assetYields"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        accumulatedYield: bigint;
        lastUpdated: bigint;
        annualYieldBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccumulatedYield"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAsset"
  ): TypedContractMethod<
    [asset: AddressLike, yieldBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAnnualYield"
  ): TypedContractMethod<
    [asset: AddressLike, rawPrice: BigNumberish, yieldBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateYield"
  ): TypedContractMethod<
    [asset: AddressLike, rawPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AnnualYieldSet"
  ): TypedContractEvent<
    AnnualYieldSetEvent.InputTuple,
    AnnualYieldSetEvent.OutputTuple,
    AnnualYieldSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "YieldUpdated"
  ): TypedContractEvent<
    YieldUpdatedEvent.InputTuple,
    YieldUpdatedEvent.OutputTuple,
    YieldUpdatedEvent.OutputObject
  >;

  filters: {
    "AnnualYieldSet(address,uint256,uint256)": TypedContractEvent<
      AnnualYieldSetEvent.InputTuple,
      AnnualYieldSetEvent.OutputTuple,
      AnnualYieldSetEvent.OutputObject
    >;
    AnnualYieldSet: TypedContractEvent<
      AnnualYieldSetEvent.InputTuple,
      AnnualYieldSetEvent.OutputTuple,
      AnnualYieldSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "YieldUpdated(address,uint256,uint256)": TypedContractEvent<
      YieldUpdatedEvent.InputTuple,
      YieldUpdatedEvent.OutputTuple,
      YieldUpdatedEvent.OutputObject
    >;
    YieldUpdated: TypedContractEvent<
      YieldUpdatedEvent.InputTuple,
      YieldUpdatedEvent.OutputTuple,
      YieldUpdatedEvent.OutputObject
    >;
  };
}
