/**
 * sync-vantage.ts
 *
 * Synchronizes contract artifacts from a local bcellar-monorepo repository.
 *
 * Usage:
 *   pnpm sync                           # uses ../bcellar-monorepo by default
 *   pnpm sync /Users/xxx/xxx/bcellar-monorepo # explicit path
 *   VANTAGE_PROTOCOL_PATH=... pnpm sync # via env var
 */

import * as fs from "fs/promises";
import fse from "fs-extra";
import * as path from "path";
import { spawnSync } from "child_process";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const AUTO_GENERATED_HEADER = `\
// This file is auto-generated by scripts/sync-vantage.ts
// Do not edit manually — run \`pnpm sync\` to regenerate.

`;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert a string like "arbitrum-sepolia_v2" → "ARBITRUM_SEPOLIA_V2" */
function toScreamingSnakeCase(str: string): string {
  return str
    .replace(/[-./]/g, "_")
    .replace(/([a-z])([A-Z])/g, "$1_$2")
    .toUpperCase()
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");
}

/** Recursively collect files matching a predicate. */
async function findFiles(dir: string, filter: (filename: string) => boolean): Promise<string[]> {
  if (!(await fse.pathExists(dir))) return [];
  const results: string[] = [];

  async function walk(current: string): Promise<void> {
    const entries = await fs.readdir(current, { withFileTypes: true });
    for (const entry of entries) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
      } else if (filter(entry.name)) {
        results.push(full);
      }
    }
  }

  await walk(dir);
  return results;
}

// ---------------------------------------------------------------------------
// Sync: Addresses
// ---------------------------------------------------------------------------

/**
 * Scans all JSON files in deployments/ and generates src/vantage/addresses.ts
 * with per-network named exports, e.g.:
 *   export const ARBITRUM_SEPOLIA_V2_VAULT = "0x..." as const;
 */
async function syncAddresses(protocolPath: string, destRoot: string): Promise<void> {
  const deploymentsDir = path.join(protocolPath, "deployments");

  if (!(await fse.pathExists(deploymentsDir))) {
    console.warn("  ⚠️  deployments/ not found, skipping addresses sync.");
    return;
  }

  const deploymentFiles = (await fs.readdir(deploymentsDir)).filter((f) => f.endsWith(".json"));

  if (deploymentFiles.length === 0) {
    console.warn("  ⚠️  No deployment JSON files found.");
    return;
  }

  const lines: string[] = [AUTO_GENERATED_HEADER];

  for (const file of deploymentFiles.sort()) {
    const networkName = path.basename(file, ".json"); // e.g., "arbitrum-sepolia_v2"
    const prefix = toScreamingSnakeCase(networkName); // e.g., "ARBITRUM_SEPOLIA_V2"
    const data: Record<string, unknown> = await fse.readJson(path.join(deploymentsDir, file));

    const exports: string[] = [];

    for (const [contractName, value] of Object.entries(data)) {
      let address: string | undefined;

      if (typeof value === "string") {
        address = value;
      } else if (
        typeof value === "object" &&
        value !== null &&
        "address" in value &&
        typeof (value as Record<string, unknown>).address === "string"
      ) {
        address = (value as Record<string, string>).address;
      }

      if (address) {
        const exportName = `${prefix}_${toScreamingSnakeCase(contractName)}`;
        exports.push(`export const ${exportName} = "${address}" as const;`);
      }
    }

    if (exports.length > 0) {
      lines.push(`// Network: ${networkName}`);
      lines.push(...exports);
      lines.push("");
    }
  }

  await fse.outputFile(path.join(destRoot, "addresses.ts"), lines.join("\n"));
  console.log(`  ✅ addresses.ts — ${deploymentFiles.length} network file(s) processed`);
}

// ---------------------------------------------------------------------------
// Sync: ABIs
// ---------------------------------------------------------------------------

/**
 * Scans artifacts/contracts/**\/*.json (excludes *.dbg.json),
 * extracts only the `abi` array, and saves flattened JSON to src/vantage/abis/.
 *
 * Collision strategy: if two contracts share the same base name, the second
 * one is saved as {parentDirName}_{contractName}.json.
 */
async function syncAbis(protocolPath: string, destRoot: string): Promise<void> {
  const artifactsDir = path.join(protocolPath, "artifacts", "contracts");

  if (!(await fse.pathExists(artifactsDir))) {
    console.warn("  ⚠️  artifacts/contracts/ not found, skipping ABI sync.");
    return;
  }

  const jsonFiles = await findFiles(artifactsDir, (f) => f.endsWith(".json") && !f.endsWith(".dbg.json"));

  const destAbisDir = path.join(destRoot, "abis");
  await fse.ensureDir(destAbisDir);

  // contractName → first source path seen (for collision detection)
  const seen = new Map<string, string>();
  let count = 0;

  for (const srcFile of jsonFiles) {
    let data: Record<string, unknown>;
    try {
      data = await fse.readJson(srcFile);
    } catch {
      console.warn(`  ⚠️  Could not parse ${srcFile}, skipping.`);
      continue;
    }

    if (!Array.isArray(data.abi)) continue; // not a contract artifact

    const contractName = path.basename(srcFile, ".json");

    let destName = contractName;
    if (seen.has(contractName)) {
      // e.g., artifacts/contracts/core/Vault.sol/Vault.json → "core_Vault"
      const solDir = path.dirname(srcFile); // .../Vault.sol
      const subDir = path.dirname(solDir); // .../core
      const prefix = path.basename(subDir); // "core"
      destName = `${prefix}_${contractName}`;
      console.warn(`  ⚠️  Name collision for "${contractName}" — saving as "${destName}.json"`);
    }
    seen.set(contractName, srcFile);

    await fse.outputJson(path.join(destAbisDir, `${destName}.json`), data.abi, { spaces: 2 });
    count++;
  }

  console.log(`  ✅ abis/ — ${count} ABI file(s) written`);
}

// ---------------------------------------------------------------------------
// Step 3: Generate TypeScript types with Typechain
//
// What this step does:
//   1. Reads the ABI JSON files written by syncAbis() from src/vantage/abis/
//   2. Runs `typechain --target ethers-v6` (via node_modules/.bin/typechain)
//   3. Outputs typed contract interfaces + factory classes to src/vantage/types/
//
// Generated output layout:
//   src/vantage/types/
//   ├── index.ts                     ← barrel export for all types
//   ├── common.ts                    ← shared TypedContractEvent helpers
//   ├── Vault.ts                     ← Vault contract interface (typed methods/events)
//   ├── Router.ts                    ← Router contract interface
//   └── factories/
//       ├── index.ts
//       ├── Vault__factory.ts        ← factory to deploy/connect Vault
//       └── Router__factory.ts      ← factory to deploy/connect Router
//
// Usage in application code (ethers-v6):
//   import { Vault__factory } from "src/vantage/types";
//   const vault = Vault__factory.connect(address, provider);
//   await vault.deposit(amount);     ← fully typed
//
// Requires devDependencies: typechain, @typechain/ethers-v6
// ---------------------------------------------------------------------------

async function runTypechain(destRoot: string): Promise<void> {
  const abisDir = path.join(destRoot, "abis");
  const abiFiles = (await fs.readdir(abisDir)).filter((f) =>
    f.endsWith(".json")
  );

  if (abiFiles.length === 0) {
    console.warn("  ⚠️  No ABI files found — skipping Typechain.");
    return;
  }

  const typesDir = path.join(destRoot, "types");
  await fse.emptyDir(typesDir);

  // Paths must be relative to cwd for the typechain CLI
  const outDir = path.relative(process.cwd(), typesDir);
  const glob = path.relative(process.cwd(), path.join(abisDir, "*.json"));

  // Use the locally installed typechain binary (node_modules/.bin/typechain)
  const typechainBin = path.resolve(
    process.cwd(),
    "node_modules",
    ".bin",
    "typechain"
  );

  console.log(`  Running: typechain --target ethers-v6 --out-dir ${outDir} "${glob}"`);

  // ===== Typechain execution =====
  const result = spawnSync(
    typechainBin,
    ["--target", "ethers-v6", "--out-dir", outDir, glob],
    { stdio: "inherit", cwd: process.cwd() }
  );
  // ================================

  if (result.error) {
    throw new Error(`Failed to launch Typechain: ${result.error.message}`);
  }
  if (result.status !== 0) {
    throw new Error(`Typechain exited with status ${result.status}`);
  }

  const generated = await findFiles(typesDir, (f) => f.endsWith(".ts"));
  console.log(`  ✅ types/ — ${generated.length} file(s) generated by Typechain`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const protocolPath =
    process.env.VANTAGE_PROTOCOL_PATH || process.argv[2] || path.resolve(process.cwd(), "..", "bcellar-monorepo");

  console.log(`\n🔍 Source: ${protocolPath}`);

  if (!(await fse.pathExists(protocolPath))) {
    console.error(`\n❌  bcellar-monorepo not found at:\n   ${protocolPath}`);
    console.error("\n   Please check the path and try one of:");
    console.error("   • VANTAGE_PROTOCOL_PATH=/path/to/repo pnpm sync");
    console.error("   • pnpm sync /path/to/repo");
    process.exit(1);
  }

  const destRoot = path.resolve(process.cwd(), "src", "vantage");

  console.log(`🗑  Cleaning ${path.relative(process.cwd(), destRoot)}/...`);
  await fse.emptyDir(destRoot);

  console.log("\n📦 Syncing addresses...");
  await syncAddresses(protocolPath, destRoot);

  console.log("\n📦 Syncing ABIs...");
  await syncAbis(protocolPath, destRoot);

  console.log("\n⚙️  Generating types with Typechain...");
  await runTypechain(destRoot);

  console.log("\n🎉 Sync complete!");
  console.log("   Run `pnpm sync:test` to validate, then `pnpm tscheck` for type safety.");
}

main().catch((err: Error) => {
  console.error("\n❌ Sync failed:", err.message);
  process.exit(1);
});
