/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { AssetRegistry, AssetRegistryInterface } from "../AssetRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "initialOwner",
        type: "address",
      },
      {
        internalType: "address",
        name: "_yieldAccumulator",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "AssetAlreadyRegistered",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "AssetNotRegistered",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "provided",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minimum",
        type: "uint256",
      },
    ],
    name: "InvalidLeverage",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "provided",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maximum",
        type: "uint256",
      },
    ],
    name: "InvalidMaintenanceMargin",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "provided",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maximum",
        type: "uint256",
      },
    ],
    name: "InvalidMarginFee",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "priceFeed",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isEnabled",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isShortable",
        type: "bool",
      },
    ],
    name: "AssetConfigUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isEnabled",
        type: "bool",
      },
    ],
    name: "AssetEnabled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum AssetRegistry.AssetType",
        name: "assetType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "address",
        name: "priceFeed",
        type: "address",
      },
    ],
    name: "AssetRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "fundingRateFactor",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "maxFundingRate",
        type: "uint256",
      },
    ],
    name: "FundingParamsUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "maxLeverage",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "maintenanceMarginBps",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "marginFeeBps",
        type: "uint256",
      },
    ],
    name: "RiskConfigUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "requiresWeekendLock",
        type: "bool",
      },
    ],
    name: "WeekendLockUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "LEVERAGE_PRECISION",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_MAINTENANCE_MARGIN_BPS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_MARGIN_FEE_BPS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_LEVERAGE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "allAssets",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "assets",
    outputs: [
      {
        internalType: "enum AssetRegistry.AssetType",
        name: "assetType",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "priceFeed",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "decimals",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isEnabled",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "isShortable",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "isRegistered",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "maxLeverage",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxGlobalLongSize",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxGlobalShortSize",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maintenanceMarginBps",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "marginFeeBps",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "requiresWeekendLock",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "fundingRateFactor",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxFundingRate",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllAssets",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getAssetInfo",
    outputs: [
      {
        components: [
          {
            internalType: "enum AssetRegistry.AssetType",
            name: "assetType",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "priceFeed",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "decimals",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isEnabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isShortable",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "accumulatedYield",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxLeverage",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxGlobalLongSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxGlobalShortSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maintenanceMarginBps",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "marginFeeBps",
            type: "uint256",
          },
        ],
        internalType: "struct AssetRegistry.AssetInfo",
        name: "info",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getAssetRiskInfo",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "maxLeverage",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxGlobalLongSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxGlobalShortSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maintenanceMarginBps",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "marginFeeBps",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "requiresWeekendLock",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "fundingRateFactor",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxFundingRate",
            type: "uint256",
          },
        ],
        internalType: "struct AssetRegistry.AssetRiskInfo",
        name: "info",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getFundingParams",
    outputs: [
      {
        internalType: "uint256",
        name: "fundingRateFactor",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxFundingRate",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getRequiresWeekendLock",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "enum AssetRegistry.AssetType",
        name: "assetType",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "priceFeed",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "decimals_",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isShortable",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "initialYieldBps",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "maxLeverage",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxGlobalLongSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxGlobalShortSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maintenanceMarginBps",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "marginFeeBps",
            type: "uint256",
          },
        ],
        internalType: "struct AssetRegistry.RiskParams",
        name: "risk",
        type: "tuple",
      },
    ],
    name: "registerAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
    ],
    name: "setEnabled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "fundingRateFactor",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxFundingRate",
        type: "uint256",
      },
    ],
    name: "setFundingParams",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "bool",
        name: "requiresLock",
        type: "bool",
      },
    ],
    name: "setRequiresWeekendLock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "address",
        name: "priceFeed",
        type: "address",
      },
      {
        internalType: "bool",
        name: "isEnabled",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "isShortable",
        type: "bool",
      },
    ],
    name: "updateAssetConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "maxLeverage",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxGlobalLongSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxGlobalShortSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maintenanceMarginBps",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "marginFeeBps",
            type: "uint256",
          },
        ],
        internalType: "struct AssetRegistry.RiskParams",
        name: "risk",
        type: "tuple",
      },
    ],
    name: "updateRiskConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "yieldAccumulator",
    outputs: [
      {
        internalType: "contract YieldAccumulator",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AssetRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): AssetRegistryInterface {
    return new Interface(_abi) as AssetRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AssetRegistry {
    return new Contract(address, _abi, runner) as unknown as AssetRegistry;
  }
}
