/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ERC3643Adapter, ERC3643AdapterInterface } from "../ERC3643Adapter";

const _abi = [
  {
    inputs: [],
    name: "adapterType",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isCompliant",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ERC3643Adapter__factory {
  static readonly abi = _abi;
  static createInterface(): ERC3643AdapterInterface {
    return new Interface(_abi) as ERC3643AdapterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ERC3643Adapter {
    return new Contract(address, _abi, runner) as unknown as ERC3643Adapter;
  }
}
