/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IAssetRegistry, IAssetRegistryInterface } from "../IAssetRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "complianceAdapters",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getAssetInfo",
    outputs: [
      {
        components: [
          {
            internalType: "enum IAssetRegistry.AssetType",
            name: "assetType",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "priceFeed",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "decimals",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isEnabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isShortable",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "accumulatedYield",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxLeverage",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxGlobalLongSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxGlobalShortSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maintenanceMarginBps",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "marginFeeBps",
            type: "uint256",
          },
        ],
        internalType: "struct IAssetRegistry.AssetInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getAssetRiskInfo",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "maxLeverage",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxGlobalLongSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxGlobalShortSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maintenanceMarginBps",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "liquidationFeeBps",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "marginFeeBps",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "requiresWeekendLock",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "fundingRateFactor",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxFundingRate",
            type: "uint256",
          },
        ],
        internalType: "struct IAssetRegistry.AssetRiskInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getFundingParams",
    outputs: [
      {
        internalType: "uint256",
        name: "fundingRateFactor",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxFundingRate",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getMinLegalUnit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getRequiresWeekendLock",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRestrictedAssets",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "isMarketOpen",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "utilizationCapBps",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAssetRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetRegistryInterface {
    return new Interface(_abi) as IAssetRegistryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAssetRegistry {
    return new Contract(address, _abi, runner) as unknown as IAssetRegistry;
  }
}
