/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IYieldAccumulator, IYieldAccumulatorInterface } from "../IYieldAccumulator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getAccumulatedYield",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getEffectiveYieldBps",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "rawPrice",
        type: "uint256",
      },
    ],
    name: "updateYield",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IYieldAccumulator__factory {
  static readonly abi = _abi;
  static createInterface(): IYieldAccumulatorInterface {
    return new Interface(_abi) as IYieldAccumulatorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IYieldAccumulator {
    return new Contract(address, _abi, runner) as unknown as IYieldAccumulator;
  }
}
