/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { MockVantageRwaOracle, MockVantageRwaOracleInterface } from "../MockVantageRwaOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "date",
        type: "uint256",
      },
    ],
    name: "priceForDate",
    outputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "confirmed",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "date",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "confirmed",
        type: "bool",
      },
    ],
    name: "setPriceForDate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class MockVantageRwaOracle__factory {
  static readonly abi = _abi;
  static createInterface(): MockVantageRwaOracleInterface {
    return new Interface(_abi) as MockVantageRwaOracleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockVantageRwaOracle {
    return new Contract(address, _abi, runner) as unknown as MockVantageRwaOracle;
  }
}
