/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Periphery_ILPManager, Periphery_ILPManagerInterface } from "../Periphery_ILPManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "addLiquidityFor",
    outputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Periphery_ILPManager__factory {
  static readonly abi = _abi;
  static createInterface(): Periphery_ILPManagerInterface {
    return new Interface(_abi) as Periphery_ILPManagerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Periphery_ILPManager {
    return new Contract(address, _abi, runner) as unknown as Periphery_ILPManager;
  }
}
