/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { VaultFactory, VaultFactoryInterface } from "../VaultFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "governance",
        type: "address",
      },
      {
        internalType: "address",
        name: "_hub",
        type: "address",
      },
      {
        internalType: "address",
        name: "_assetRegistry",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newHubOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newRegistryOwner",
        type: "address",
      },
    ],
    name: "FactoryControlRenounced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "vault",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "debtCeiling",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "governance",
        type: "address",
      },
    ],
    name: "VaultCreated",
    type: "event",
  },
  {
    inputs: [],
    name: "assetRegistry",
    outputs: [
      {
        internalType: "contract AssetRegistry",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "debtCeiling",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "lpManager",
        type: "address",
      },
      {
        internalType: "address",
        name: "complianceRegistry",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "requiredKYCLevel",
        type: "uint8",
      },
      {
        components: [
          {
            internalType: "enum AssetRegistry.AssetType",
            name: "assetType",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "priceFeed",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "decimals",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isShortable",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "initialYieldBps",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "maxLeverage",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "maxGlobalLongSize",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "maxGlobalShortSize",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "maintenanceMarginBps",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "marginFeeBps",
                type: "uint256",
              },
            ],
            internalType: "struct AssetRegistry.RiskParams",
            name: "risk",
            type: "tuple",
          },
        ],
        internalType: "struct VaultFactory.AssetParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "createVault",
    outputs: [
      {
        internalType: "address",
        name: "vaultAddr",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "deployedVaults",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "deployedVaultsCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "hub",
    outputs: [
      {
        internalType: "contract SharedPayoutHub",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceFactoryControl",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class VaultFactory__factory {
  static readonly abi = _abi;
  static createInterface(): VaultFactoryInterface {
    return new Interface(_abi) as VaultFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VaultFactory {
    return new Contract(address, _abi, runner) as unknown as VaultFactory;
  }
}
